using System.Text;
using System.Text.Json;
using Ueci.Unreal;

namespace Ueci.Plugin;

public sealed record UnrealPluginHostLayout(
    string Root,
    string ProjectPath,
    string PluginRoot,
    string PluginDescriptorPath,
    string GameTargetName,
    string EditorTargetName);

public static class UnrealPluginHostProject
{
    public const string GameTargetName = "UECIHost";
    public const string EditorTargetName = "UECIHostEditor";

    public static Task<UnrealPluginHostLayout> PrepareAsync(
        string engineRoot,
        UnrealPluginDescriptor plugin,
        CancellationToken cancellationToken = default)
        => PrepareAsync(engineRoot, plugin, workspaceBaseDirectory: null, cancellationToken);

    public static async Task<UnrealPluginHostLayout> PrepareAsync(
        string engineRoot,
        UnrealPluginDescriptor plugin,
        string? workspaceBaseDirectory,
        CancellationToken cancellationToken = default)
    {
        UnrealEngineCompatibility compatibility = await UnrealEngineCompatibility.DetectAsync(
            engineRoot,
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return await PrepareAsync(
            engineRoot,
            plugin,
            workspaceBaseDirectory,
            compatibility,
            cancellationToken).ConfigureAwait(false);
    }

    public static async Task<UnrealPluginHostLayout> PrepareAsync(
        string engineRoot,
        UnrealPluginDescriptor plugin,
        string? workspaceBaseDirectory,
        UnrealEngineCompatibility compatibility,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(engineRoot);
        ArgumentNullException.ThrowIfNull(plugin);
        ArgumentNullException.ThrowIfNull(compatibility);

        string workspaceBase = workspaceBaseDirectory is null
            ? Path.Combine(Path.GetFullPath(engineRoot), ".ueci", "plugin-work")
            : Path.GetFullPath(workspaceBaseDirectory);
        string workspace = Path.Combine(workspaceBase, Sanitize(plugin.Name));
        string pluginRoot = Path.Combine(workspace, "Plugins", plugin.Name);
        if (Directory.Exists(workspace)) Directory.Delete(workspace, recursive: true);
        Directory.CreateDirectory(pluginRoot);

        string sourcePluginRoot = Path.GetDirectoryName(plugin.DescriptorPath)
            ?? throw new InvalidDataException("Unable to determine plugin source directory.");
        CopyDirectory(sourcePluginRoot, pluginRoot, relative: string.Empty);

        string copiedDescriptor = Path.Combine(pluginRoot, Path.GetFileName(plugin.DescriptorPath));
        string projectPath = Path.Combine(workspace, "UECIHost.uproject");
        await WriteProjectAsync(projectPath, plugin.Name, compatibility, cancellationToken).ConfigureAwait(false);
        await WriteHostSourceAsync(workspace, plugin, compatibility, cancellationToken).ConfigureAwait(false);
        await WriteBuildConfigurationAsync(engineRoot, workspace, compatibility, cancellationToken).ConfigureAwait(false);

        return new UnrealPluginHostLayout(
            workspace,
            projectPath,
            pluginRoot,
            copiedDescriptor,
            GameTargetName,
            EditorTargetName);
    }

    private static async Task WriteProjectAsync(
        string path,
        string pluginName,
        UnrealEngineCompatibility compatibility,
        CancellationToken cancellationToken)
    {
        var payload = new Dictionary<string, object?>
        {
            ["FileVersion"] = 3,
            ["Category"] = "UECI",
            ["Description"] = "Ephemeral host project generated by UECI.",
            ["Modules"] = new[]
            {
                new { Name = GameTargetName, Type = "Runtime", LoadingPhase = "Default" },
            },
            ["Plugins"] = new[] { new { Name = pluginName, Enabled = true } },
        };
        // Before TargetRules gained bAllowEnginePluginsEnabledByDefault, the project
        // descriptor already had the inverse switch. Without it UE5.1 enables Paper2D
        // (and therefore Engine/ApplicationCore) behind the back of the deliberately lean
        // synthetic target. Keep the plugin set explicit at the project boundary.
        if (compatibility.SupportsDisableEnginePluginsByDefaultProject)
        {
            payload["DisableEnginePluginsByDefault"] = true;
        }
        string json = JsonSerializer.Serialize(payload, new JsonSerializerOptions { WriteIndented = true });
        await File.WriteAllTextAsync(path, json + Environment.NewLine, cancellationToken).ConfigureAwait(false);
    }

    private static async Task WriteHostSourceAsync(
        string workspace,
        UnrealPluginDescriptor plugin,
        UnrealEngineCompatibility compatibility,
        CancellationToken cancellationToken)
    {
        string source = Path.Combine(workspace, "Source");
        string module = Path.Combine(source, GameTargetName);
        Directory.CreateDirectory(module);

        string[] runtimeModules = plugin.Modules
            .Where(candidate => !candidate.IsEditorOnly && !candidate.IsProgramOnly)
            .Select(candidate => candidate.Name)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(name => name, StringComparer.Ordinal)
            .ToArray();
        string[] editorModules = plugin.Modules
            .Where(candidate => !candidate.IsProgramOnly)
            .Select(candidate => candidate.Name)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(name => name, StringComparer.Ordinal)
            .ToArray();

        string runtimeTarget = BuildTargetSource(
            GameTargetName,
            "Game",
            runtimeModules.Prepend(GameTargetName),
            plugin.Name,
            compatibility,
            runtime: true);
        string editorTarget = BuildTargetSource(
            EditorTargetName,
            "Editor",
            editorModules.Prepend(GameTargetName),
            plugin.Name,
            compatibility,
            runtime: false);

        await File.WriteAllTextAsync(
            Path.Combine(source, GameTargetName + ".Target.cs"),
            runtimeTarget,
            cancellationToken).ConfigureAwait(false);
        await File.WriteAllTextAsync(
            Path.Combine(source, EditorTargetName + ".Target.cs"),
            editorTarget,
            cancellationToken).ConfigureAwait(false);

        string moduleRules = compatibility.SupportsReadOnlyTargetRules
            ? $$"""
              using UnrealBuildTool;

              public class {{GameTargetName}} : ModuleRules
              {
                  public {{GameTargetName}}(ReadOnlyTargetRules Target) : base(Target)
                  {
                      PrivateDependencyModuleNames.Add("Core");
                  }
              }
              """
            : $$"""
              using UnrealBuildTool;

              public class {{GameTargetName}} : ModuleRules
              {
                  public {{GameTargetName}}(TargetInfo Target)
                  {
                      PrivateDependencyModuleNames.Add("Core");
                  }
              }
              """;
        await File.WriteAllTextAsync(
            Path.Combine(module, GameTargetName + ".Build.cs"),
            moduleRules + Environment.NewLine,
            cancellationToken).ConfigureAwait(false);

        string cpp = compatibility.SupportsGlobalDefinitions
            ? """
              #include "CoreTypes.h"
              #include "CoreGlobals.h"
              #include "Modules/ModuleManager.h"

              #ifndef UECI_SYNTHETIC_PROGRAM
              #define UECI_SYNTHETIC_PROGRAM 0
              #endif

              #if UECI_SYNTHETIC_PROGRAM
              TCHAR GInternalProjectName[64] = TEXT("UECIHost");
              const TCHAR* GForeignEngineDir = nullptr;

              int main(int, char**)
              {
                  return 0;
              }
              #endif

              IMPLEMENT_MODULE(FDefaultModuleImpl, UECIHost)
              """
            : """
              #include "Modules/ModuleManager.h"

              IMPLEMENT_MODULE(FDefaultModuleImpl, UECIHost)
              """;
        await File.WriteAllTextAsync(
            Path.Combine(module, GameTargetName + ".cpp"),
            cpp + Environment.NewLine,
            cancellationToken).ConfigureAwait(false);
    }

    private static string BuildTargetSource(
        string classBaseName,
        string targetType,
        IEnumerable<string> moduleNames,
        string pluginName,
        UnrealEngineCompatibility compatibility,
        bool runtime)
    {
        string[] modules = moduleNames.Distinct(StringComparer.Ordinal).ToArray();
        var text = new StringBuilder();
        text.AppendLine("using UnrealBuildTool;");
        if (!compatibility.SupportsExtraModuleNames) text.AppendLine("using System.Collections.Generic;");
        text.AppendLine();
        text.AppendLine($"public class {classBaseName}Target : TargetRules");
        text.AppendLine("{");
        string targetBase = compatibility.SupportsTargetInfoBaseConstructor ? " : base(Target)" : string.Empty;
        text.AppendLine($"    public {classBaseName}Target(TargetInfo Target){targetBase}");
        text.AppendLine("    {");
        text.AppendLine($"        Type = TargetType.{targetType};");

        AppendTargetAssignment(text, compatibility, "TargetLinkType", "        LinkType = TargetLinkType.Modular;");
        if (runtime) AppendTargetAssignment(text, compatibility, "LaunchModuleName", $"        LaunchModuleName = {ToCSharpStringLiteral(GameTargetName)};");
        if (runtime && compatibility.SupportsUniqueBuildEnvironment)
            text.AppendLine("        BuildEnvironment = TargetBuildEnvironment.Unique;");
        if (compatibility.SupportsDefaultBuildSettings)
            text.AppendLine("        DefaultBuildSettings = BuildSettingsVersion.Latest;");
        if (compatibility.SupportsIncludeOrderVersion)
            text.AppendLine("        IncludeOrderVersion = EngineIncludeOrderVersion.Latest;");

        if (runtime)
        {
            AppendBool(text, compatibility, "bCompileAgainstEngine", false);
            AppendBool(text, compatibility, "bCompileAgainstCoreUObject", false);
            if (compatibility.SupportsCompileAgainstApplicationCore)
                text.AppendLine("        bCompileAgainstApplicationCore = false;");
            AppendBool(text, compatibility, "bBuildDeveloperTools", false);
            if (compatibility.SupportsBuildTargetDeveloperTools)
                text.AppendLine("        bBuildTargetDeveloperTools = false;");
            if (compatibility.SupportsForceBuildTargetPlatforms)
                text.AppendLine("        bForceBuildTargetPlatforms = false;");
            if (compatibility.SupportsForceBuildShaderFormats)
                text.AppendLine("        bForceBuildShaderFormats = false;");
            if (compatibility.SupportsNeedsExtraShaderFormatsOverride)
                text.AppendLine("        bNeedsExtraShaderFormatsOverride = false;");
            if (compatibility.SupportsCompileWithPluginSupport)
                text.AppendLine("        bCompileWithPluginSupport = true;");
            if (compatibility.SupportsIncludePluginsForTargetPlatforms)
                text.AppendLine("        bIncludePluginsForTargetPlatforms = true;");
            if (compatibility.SupportsAllowEnginePluginsEnabledByDefault)
                text.AppendLine("        bAllowEnginePluginsEnabledByDefault = false;");
            if (compatibility.SupportsAdditionalPlugins)
                text.AppendLine($"        AdditionalPlugins.Add({ToCSharpStringLiteral(pluginName)});");
            AppendBool(text, compatibility, "bUsesSlate", false);
            if (compatibility.SupportsCompileIcu) text.AppendLine("        bCompileICU = false;");
            if (compatibility.SupportsEnableTrace) text.AppendLine("        bEnableTrace = false;");
            if (compatibility.SupportsRuntimeSymbolFiles) text.AppendLine("        bAllowRuntimeSymbolFiles = false;");
            if (compatibility.SupportsGlobalDefinitions)
                text.AppendLine("        GlobalDefinitions.Add(\"UECI_SYNTHETIC_PROGRAM=1\");");
        }

        if (compatibility.SupportsExtraModuleNames)
        {
            foreach (string module in modules)
                text.AppendLine($"        ExtraModuleNames.Add({ToCSharpStringLiteral(module)});");
        }
        text.AppendLine("    }");

        if (!compatibility.SupportsTargetLinkType && compatibility.SupportsShouldCompileMonolithic)
        {
            // Before TargetLinkType.Modular, UBT exposed the same choice through this virtual.
            // Keep the synthetic Game target modular so -Module emits a standalone plugin binary.
            text.AppendLine();
            text.AppendLine("    public override bool ShouldCompileMonolithic(UnrealTargetPlatform InPlatform, UnrealTargetConfiguration InConfiguration)");
            text.AppendLine("    {");
            text.AppendLine("        return false;");
            text.AppendLine("    }");
        }

        if (!compatibility.SupportsExtraModuleNames)
        {
            // UE4's original TargetRules API populated modules through SetupBinaries rather than
            // the later ExtraModuleNames property.
            text.AppendLine();
            text.AppendLine("    public override void SetupBinaries(TargetInfo Target, ref List<UEBuildBinaryConfiguration> OutBuildBinaryConfigurations, ref List<string> OutExtraModuleNames)");
            text.AppendLine("    {");
            foreach (string module in modules)
                text.AppendLine($"        OutExtraModuleNames.Add({ToCSharpStringLiteral(module)});");
            text.AppendLine("    }");
        }
        text.AppendLine("}");
        return text.ToString();
    }

    private static void AppendBool(
        StringBuilder text,
        UnrealEngineCompatibility compatibility,
        string member,
        bool value)
    {
        if (compatibility.SupportsTargetMember(member))
            text.AppendLine($"        {member} = {(value ? "true" : "false")};");
    }

    private static void AppendTargetAssignment(
        StringBuilder text,
        UnrealEngineCompatibility compatibility,
        string token,
        string assignment)
    {
        if (compatibility.SupportsTargetMember(token)) text.AppendLine(assignment);
    }

    private static string ToCSharpStringLiteral(string value)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(value);
        return "\"" + value
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal) + "\"";
    }

    private static async Task WriteBuildConfigurationAsync(
        string engineRoot,
        string workspace,
        UnrealEngineCompatibility compatibility,
        CancellationToken cancellationToken)
    {
        // Legacy UE4 configuration schemas changed repeatedly and Linux does not need the Windows
        // distributed executors disabled explicitly. Keep UE4 entirely free of generated modern
        // XML; feature-filtered BuildConfiguration.xml starts with UE5.
        if (compatibility.Version.Major < 5) return;

        bool hasKnownFields = compatibility.SupportsAllowUbaExecutorConfig
            || compatibility.SupportsAllowUbaLocalExecutorConfig
            || compatibility.SupportsAllowXgeConfig
            || compatibility.SupportsAllowFastBuildConfig
            || compatibility.SupportsAllowSndbsConfig
            || compatibility.SupportsDisableDumpSymsConfig;
        if (!hasKnownFields) return;

        string[] directories =
        [
            Path.Combine(Path.GetFullPath(engineRoot), "Engine", "Saved", "UnrealBuildTool"),
            Path.Combine(workspace, "Saved", "UnrealBuildTool"),
        ];
        foreach (string directory in directories)
        {
            await UnrealBuildToolConfiguration.WriteHermeticLocalExecutorAsync(
                directory,
                cancellationToken,
                compatibility).ConfigureAwait(false);
        }
    }

    private static void CopyDirectory(string sourceRoot, string destinationRoot, string relative)
    {
        string source = relative.Length == 0 ? sourceRoot : Path.Combine(sourceRoot, relative);
        string destination = relative.Length == 0 ? destinationRoot : Path.Combine(destinationRoot, relative);
        Directory.CreateDirectory(destination);

        foreach (string file in Directory.EnumerateFiles(source))
            File.Copy(file, Path.Combine(destination, Path.GetFileName(file)), overwrite: true);

        foreach (string directory in Directory.EnumerateDirectories(source))
        {
            string name = Path.GetFileName(directory);
            if (name is "Intermediate" or "Saved" or ".git" or ".ueci") continue;
            if (relative.Length == 0 && name == "Binaries")
            {
                string thirdParty = Path.Combine(directory, "ThirdParty");
                if (Directory.Exists(thirdParty))
                    CopyDirectory(sourceRoot, destinationRoot, Path.Combine("Binaries", "ThirdParty"));
                continue;
            }
            string child = relative.Length == 0 ? name : Path.Combine(relative, name);
            CopyDirectory(sourceRoot, destinationRoot, child);
        }
    }

    private static string Sanitize(string value)
    {
        char[] invalid = Path.GetInvalidFileNameChars();
        string sanitized = new(value.Select(character => invalid.Contains(character) ? '_' : character).ToArray());
        return string.IsNullOrWhiteSpace(sanitized) ? "Plugin" : sanitized;
    }
}
