using Ueci.Unreal;
using System.Text.Json;

namespace Ueci.Plugin;

public sealed record UnrealPluginHostLayout(
    string Root,
    string ProjectPath,
    string PluginRoot,
    string PluginDescriptorPath,
    string GameTargetName,
    string EditorTargetName);

public static class UnrealPluginHostProject
{
    public const string GameTargetName = "UECIHost";
    public const string EditorTargetName = "UECIHostEditor";

    public static Task<UnrealPluginHostLayout> PrepareAsync(
        string engineRoot,
        UnrealPluginDescriptor plugin,
        CancellationToken cancellationToken = default)
        => PrepareAsync(engineRoot, plugin, workspaceBaseDirectory: null, cancellationToken);

    public static async Task<UnrealPluginHostLayout> PrepareAsync(
        string engineRoot,
        UnrealPluginDescriptor plugin,
        string? workspaceBaseDirectory,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(engineRoot);
        ArgumentNullException.ThrowIfNull(plugin);

        string workspaceBase = workspaceBaseDirectory is null
            ? Path.Combine(Path.GetFullPath(engineRoot), ".ueci", "plugin-work")
            : Path.GetFullPath(workspaceBaseDirectory);
        string workspace = Path.Combine(workspaceBase, Sanitize(plugin.Name));
        string pluginRoot = Path.Combine(workspace, "Plugins", plugin.Name);
        if (Directory.Exists(workspace))
        {
            Directory.Delete(workspace, recursive: true);
        }
        Directory.CreateDirectory(pluginRoot);

        string sourcePluginRoot = Path.GetDirectoryName(plugin.DescriptorPath)
            ?? throw new InvalidDataException("Unable to determine plugin source directory.");
        CopyDirectory(sourcePluginRoot, pluginRoot, relative: string.Empty);

        string copiedDescriptor = Path.Combine(pluginRoot, Path.GetFileName(plugin.DescriptorPath));
        string projectPath = Path.Combine(workspace, "UECIHost.uproject");
        await WriteProjectAsync(projectPath, plugin.Name, cancellationToken).ConfigureAwait(false);
        await WriteHostSourceAsync(workspace, plugin, cancellationToken).ConfigureAwait(false);
        await WriteBuildConfigurationAsync(engineRoot, workspace, cancellationToken).ConfigureAwait(false);

        return new UnrealPluginHostLayout(
            workspace,
            projectPath,
            pluginRoot,
            copiedDescriptor,
            GameTargetName,
            EditorTargetName);
    }

    private static async Task WriteProjectAsync(
        string path,
        string pluginName,
        CancellationToken cancellationToken)
    {
        var payload = new
        {
            FileVersion = 3,
            Category = "UECI",
            Description = "Ephemeral host project generated by UECI.",
            Modules = new[]
            {
                new
                {
                    Name = GameTargetName,
                    Type = "Runtime",
                    LoadingPhase = "Default",
                },
            },
            Plugins = new[] { new { Name = pluginName, Enabled = true } },
        };
        string json = JsonSerializer.Serialize(payload, new JsonSerializerOptions { WriteIndented = true });
        await File.WriteAllTextAsync(path, json + Environment.NewLine, cancellationToken).ConfigureAwait(false);
    }

    private static async Task WriteHostSourceAsync(
        string workspace,
        UnrealPluginDescriptor plugin,
        CancellationToken cancellationToken)
    {
        string source = Path.Combine(workspace, "Source");
        string module = Path.Combine(source, GameTargetName);
        Directory.CreateDirectory(module);

        string[] runtimeModules = plugin.Modules
            .Where(candidate => !candidate.IsEditorOnly && !candidate.IsProgramOnly)
            .Select(candidate => candidate.Name)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(name => name, StringComparer.Ordinal)
            .ToArray();
        string[] editorModules = plugin.Modules
            .Where(candidate => !candidate.IsProgramOnly)
            .Select(candidate => candidate.Name)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(name => name, StringComparer.Ordinal)
            .ToArray();

        string runtimeExtraModules = FormatExtraModules(runtimeModules.Prepend(GameTargetName));
        string editorExtraModules = FormatExtraModules(editorModules.Prepend(GameTargetName));
        string pluginNameLiteral = ToCSharpStringLiteral(plugin.Name);

        await File.WriteAllTextAsync(
            Path.Combine(source, GameTargetName + ".Target.cs"),
            $$"""
            using UnrealBuildTool;

            public class {{GameTargetName}}Target : TargetRules
            {
                public {{GameTargetName}}Target(TargetInfo Target) : base(Target)
                {
                    // Runtime plugin modules are not valid on TargetType.Program (UE's Runtime host
                    // type explicitly excludes programs). Use a lean Game target so the plugin is
                    // compiled in the same host class it declares in its .uplugin, while retaining
                    // the modular/module-targeted build that keeps UECI's working set small.
                    //
                    // The launch module remains the tiny UECIHost harness; -Module=<plugin> means
                    // normal mounted builds only emit the requested plugin libraries and their
                    // dependencies instead of building the host executable.
                    Type = TargetType.Game;
                    LinkType = TargetLinkType.Modular;
                    LaunchModuleName = "{{GameTargetName}}";

                    // This synthetic Game target intentionally changes compile/plugin settings from
                    // UnrealGame. It must therefore own a distinct build environment; otherwise UBT
                    // rejects the target because those settings would affect shared Engine products.
                    BuildEnvironment = TargetBuildEnvironment.Unique;

                    DefaultBuildSettings = BuildSettingsVersion.Latest;
                    IncludeOrderVersion = EngineIncludeOrderVersion.Latest;

                    bCompileAgainstEngine = false;
                    bCompileAgainstCoreUObject = false;
                    bCompileAgainstApplicationCore = false;
                    bBuildDeveloperTools = false;
                    bBuildTargetDeveloperTools = false;
                    bForceBuildTargetPlatforms = false;
                    bForceBuildShaderFormats = false;
                    bNeedsExtraShaderFormatsOverride = false;
                    bCompileWithPluginSupport = true;
                    bIncludePluginsForTargetPlatforms = true;
                    bAllowEnginePluginsEnabledByDefault = false;
                    AdditionalPlugins.Add({{pluginNameLiteral}});
                    bUsesSlate = false;
                    bCompileICU = false;
                    bEnableTrace = false;

                    // This target is a compile/link harness, not a distributable executable.
                    // Linux runtime symbol generation adds dump_syms as a post-link action; the
                    // minimal mounted Engine intentionally does not carry that standalone tool.
                    bAllowRuntimeSymbolFiles = false;

                    // Keep a tiny non-running launch entrypoint available if UBT ever needs to link the
                    // synthetic host itself. Module-targeted plugin builds normally do not build it.
                    GlobalDefinitions.Add("UECI_SYNTHETIC_PROGRAM=1");
            {{runtimeExtraModules}}
                }
            }
            """ + Environment.NewLine,
            cancellationToken).ConfigureAwait(false);

        await File.WriteAllTextAsync(
            Path.Combine(source, EditorTargetName + ".Target.cs"),
            $$"""
            using UnrealBuildTool;

            public class {{EditorTargetName}}Target : TargetRules
            {
                public {{EditorTargetName}}Target(TargetInfo Target) : base(Target)
                {
                    Type = TargetType.Editor;
                    LinkType = TargetLinkType.Modular;
                    DefaultBuildSettings = BuildSettingsVersion.Latest;
                    IncludeOrderVersion = EngineIncludeOrderVersion.Latest;
            {{editorExtraModules}}
                }
            }
            """ + Environment.NewLine,
            cancellationToken).ConfigureAwait(false);

        await File.WriteAllTextAsync(
            Path.Combine(module, GameTargetName + ".Build.cs"),
            $$"""
            using UnrealBuildTool;

            public class {{GameTargetName}} : ModuleRules
            {
                public {{GameTargetName}}(ReadOnlyTargetRules Target) : base(Target)
                {
                    PrivateDependencyModuleNames.Add("Core");
                }
            }
            """ + Environment.NewLine,
            cancellationToken).ConfigureAwait(false);

        await File.WriteAllTextAsync(
            Path.Combine(module, GameTargetName + ".cpp"),
            """
            #include "CoreTypes.h"
            #include "CoreGlobals.h"
            #include "Modules/ModuleManager.h"

            #ifndef UECI_SYNTHETIC_PROGRAM
            #define UECI_SYNTHETIC_PROGRAM 0
            #endif

            #if UECI_SYNTHETIC_PROGRAM
            // A standalone Core-only Program normally gets these from the Engine Launch module.
            // UECI deliberately does not pull Launch into the runtime validation target, so the
            // synthetic launch module owns the three process-level symbols needed by the linker.
            TCHAR GInternalProjectName[64] = TEXT("UECIHost");
            const TCHAR* GForeignEngineDir = nullptr;

            int main(int, char**)
            {
                // The host executable is a build/link harness and is never executed by UECI.
                return 0;
            }
            #endif

            IMPLEMENT_MODULE(FDefaultModuleImpl, UECIHost)
            """ + Environment.NewLine,
            cancellationToken).ConfigureAwait(false);
    }

    private static string FormatExtraModules(IEnumerable<string> moduleNames)
    {
        return string.Join(
            Environment.NewLine,
            moduleNames
                .Distinct(StringComparer.Ordinal)
                .Select(name => $"        ExtraModuleNames.Add({ToCSharpStringLiteral(name)});"));
    }

    private static string ToCSharpStringLiteral(string value)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(value);
        return "\"" + value
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal) + "\"";
    }

    private static async Task WriteBuildConfigurationAsync(
        string engineRoot,
        string workspace,
        CancellationToken cancellationToken)
    {
        // UE 5.8 still evaluates both UBA switches when selecting an executor.
        // bAllowUBALocalExecutor is deprecated, but leaving it at its default can still
        // cause ExecutorFactory to pre-create UBA before platform/toolchain validation.
        // Write the same policy at Engine and Project scope; UnrealBuildToolRunner also
        // writes it into UECI's isolated user profile before every invocation.
        string[] directories =
        [
            Path.Combine(Path.GetFullPath(engineRoot), "Engine", "Saved", "UnrealBuildTool"),
            Path.Combine(workspace, "Saved", "UnrealBuildTool"),
        ];

        foreach (string directory in directories)
        {
            await UnrealBuildToolConfiguration.WriteHermeticLocalExecutorAsync(
                directory,
                cancellationToken).ConfigureAwait(false);
        }
    }

    private static void CopyDirectory(string sourceRoot, string destinationRoot, string relative)
    {
        string source = relative.Length == 0 ? sourceRoot : Path.Combine(sourceRoot, relative);
        string destination = relative.Length == 0 ? destinationRoot : Path.Combine(destinationRoot, relative);
        Directory.CreateDirectory(destination);

        foreach (string file in Directory.EnumerateFiles(source))
        {
            File.Copy(file, Path.Combine(destination, Path.GetFileName(file)), overwrite: true);
        }

        foreach (string directory in Directory.EnumerateDirectories(source))
        {
            string name = Path.GetFileName(directory);
            if (name is "Intermediate" or "Saved" or ".git" or ".ueci")
            {
                continue;
            }
            if (relative.Length == 0 && name == "Binaries")
            {
                string thirdParty = Path.Combine(directory, "ThirdParty");
                if (Directory.Exists(thirdParty))
                {
                    CopyDirectory(sourceRoot, destinationRoot, Path.Combine("Binaries", "ThirdParty"));
                }
                continue;
            }
            string child = relative.Length == 0 ? name : Path.Combine(relative, name);
            CopyDirectory(sourceRoot, destinationRoot, child);
        }
    }

    private static string Sanitize(string value)
    {
        char[] invalid = Path.GetInvalidFileNameChars();
        string sanitized = new(value.Select(character => invalid.Contains(character) ? '_' : character).ToArray());
        return string.IsNullOrWhiteSpace(sanitized) ? "Plugin" : sanitized;
    }
}
