<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
    <VersionPrefix>0.1.0</VersionPrefix>
    <VersionSuffix>alpha.1</VersionSuffix>
    <Authors>UECI contributors</Authors>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
  </PropertyGroup>
</Project>
