<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Ueci.Core</AssemblyName>
    <RootNamespace>Ueci</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Vfs/Linux/ueci-fuse-helper.c" />
  </ItemGroup>
</Project>
