using System.Text.Json;
using System.Text.Json.Nodes;

namespace Ueci.Unreal;

public sealed record DotNetFrameworkRequirement(string Name, Version Version);

public sealed record DotNetRuntimeConfig(IReadOnlyList<DotNetFrameworkRequirement> Frameworks)
{
    public static async Task<DotNetRuntimeConfig> ReadAsync(
        string path,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(path);
        await using FileStream stream = File.OpenRead(path);
        using JsonDocument document = await JsonDocument.ParseAsync(
            stream,
            new JsonDocumentOptions
            {
                AllowTrailingCommas = true,
                CommentHandling = JsonCommentHandling.Skip,
            },
            cancellationToken).ConfigureAwait(false);

        if (!document.RootElement.TryGetProperty("runtimeOptions", out JsonElement runtimeOptions))
        {
            throw new InvalidDataException($"Runtime config '{path}' has no runtimeOptions object.");
        }

        var frameworks = new List<DotNetFrameworkRequirement>();
        if (runtimeOptions.TryGetProperty("framework", out JsonElement framework))
        {
            frameworks.Add(ParseFramework(framework, path));
        }

        if (runtimeOptions.TryGetProperty("frameworks", out JsonElement frameworkArray))
        {
            AddFrameworkArray(frameworks, frameworkArray, path, "frameworks");
        }

        // Self-contained runtimeconfigs generated by historical .NET SDKs can record the runtime
        // they were built with under includedFrameworks rather than framework/frameworks. Treat
        // those entries as requirements while reading; PinFrameworkVersionAsync can convert that
        // shape into a framework-dependent config when UECI intentionally runs UBT on the runner SDK.
        if (runtimeOptions.TryGetProperty("includedFrameworks", out JsonElement includedFrameworkArray))
        {
            AddFrameworkArray(frameworks, includedFrameworkArray, path, "includedFrameworks");
        }

        DotNetFrameworkRequirement[] distinct = frameworks
            .GroupBy(item => item.Name, StringComparer.Ordinal)
            .Select(group => group.OrderByDescending(item => item.Version).First())
            .ToArray();

        if (distinct.Length == 0)
        {
            throw new InvalidDataException($"Runtime config '{path}' does not declare a shared framework.");
        }

        return new DotNetRuntimeConfig(distinct);
    }


    public static async Task PinFrameworkVersionAsync(
        string path,
        Version version,
        string policy = "LatestMajor",
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(path);
        ArgumentNullException.ThrowIfNull(version);
        ArgumentException.ThrowIfNullOrWhiteSpace(policy);

        string json = await File.ReadAllTextAsync(path, cancellationToken).ConfigureAwait(false);
        JsonNode root = JsonNode.Parse(
            json,
            documentOptions: new JsonDocumentOptions
            {
                AllowTrailingCommas = true,
                CommentHandling = JsonCommentHandling.Skip,
            }) ?? throw new InvalidDataException($"Runtime config '{path}' is empty.");
        JsonObject rootObject = root as JsonObject
            ?? throw new InvalidDataException($"Runtime config '{path}' is not a JSON object.");
        JsonObject runtimeOptions = rootObject["runtimeOptions"] as JsonObject
            ?? throw new InvalidDataException($"Runtime config '{path}' has no runtimeOptions object.");

        string versionText = FormatRuntimeVersion(version);
        bool updated = TryPinFramework(runtimeOptions["framework"], versionText)
            | TryPinFrameworkArray(runtimeOptions["frameworks"], versionText);

        // A self-contained config is not usable with `dotnet --fx-version`. When the old Epic host
        // cannot run on the current distro and UECI recompiles UBT with the runner SDK, convert the
        // historical includedFrameworks shape to an ordinary framework-dependent declaration.
        if (!updated && runtimeOptions["includedFrameworks"] is JsonArray includedFrameworks)
        {
            JsonArray converted = new();
            foreach (JsonNode? item in includedFrameworks)
            {
                if (item is not JsonObject source) continue;
                JsonObject candidate = (JsonObject)source.DeepClone();
                if (TryPinFramework(candidate, versionText)) updated = true;
                converted.Add(candidate);
            }

            if (converted.Count == 1)
            {
                runtimeOptions["framework"] = converted[0]?.DeepClone();
                runtimeOptions.Remove("frameworks");
            }
            else if (converted.Count > 1)
            {
                runtimeOptions["frameworks"] = converted;
                runtimeOptions.Remove("framework");
            }
            runtimeOptions.Remove("includedFrameworks");
        }

        // Some SDK-generated configs omit all framework metadata for self-contained outputs. UECI
        // has deliberately rebuilt this managed executable for the runner runtime, so synthesize the
        // one shared framework UBT actually needs instead of rejecting an otherwise valid bootstrap.
        if (!updated)
        {
            runtimeOptions["framework"] = new JsonObject
            {
                ["name"] = "Microsoft.NETCore.App",
                ["version"] = versionText,
            };
            runtimeOptions.Remove("frameworks");
            runtimeOptions.Remove("includedFrameworks");
        }

        runtimeOptions["rollForward"] = policy;
        await WriteRuntimeConfigAsync(path, rootObject, cancellationToken).ConfigureAwait(false);
    }

    public static async Task EnsureRollForwardAsync(
        string path,
        string policy = "LatestMajor",
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(path);
        ArgumentException.ThrowIfNullOrWhiteSpace(policy);

        string json = await File.ReadAllTextAsync(path, cancellationToken).ConfigureAwait(false);
        JsonNode root = JsonNode.Parse(
            json,
            documentOptions: new JsonDocumentOptions
            {
                AllowTrailingCommas = true,
                CommentHandling = JsonCommentHandling.Skip,
            }) ?? throw new InvalidDataException($"Runtime config '{path}' is empty.");
        JsonObject rootObject = root as JsonObject
            ?? throw new InvalidDataException($"Runtime config '{path}' is not a JSON object.");
        JsonObject runtimeOptions = rootObject["runtimeOptions"] as JsonObject
            ?? throw new InvalidDataException($"Runtime config '{path}' has no runtimeOptions object.");
        runtimeOptions["rollForward"] = policy;

        await WriteRuntimeConfigAsync(path, rootObject, cancellationToken).ConfigureAwait(false);
    }

    private static void AddFrameworkArray(
        List<DotNetFrameworkRequirement> destination,
        JsonElement value,
        string sourcePath,
        string propertyName)
    {
        if (value.ValueKind != JsonValueKind.Array)
        {
            throw new InvalidDataException(
                $"Runtime config '{sourcePath}' has an invalid {propertyName} value.");
        }

        foreach (JsonElement item in value.EnumerateArray())
        {
            destination.Add(ParseFramework(item, sourcePath));
        }
    }

    private static bool TryPinFramework(JsonNode? node, string versionText)
    {
        if (node is not JsonObject framework
            || !string.Equals((string?)framework["name"], "Microsoft.NETCore.App", StringComparison.Ordinal))
        {
            return false;
        }

        framework["version"] = versionText;
        return true;
    }

    private static bool TryPinFrameworkArray(JsonNode? node, string versionText)
    {
        if (node is not JsonArray frameworks) return false;
        bool updated = false;
        foreach (JsonNode? item in frameworks)
        {
            updated |= TryPinFramework(item, versionText);
        }
        return updated;
    }

    private static string FormatRuntimeVersion(Version version)
    {
        int build = version.Build >= 0 ? version.Build : 0;
        return $"{version.Major}.{version.Minor}.{build}";
    }

    private static async Task WriteRuntimeConfigAsync(
        string path,
        JsonObject rootObject,
        CancellationToken cancellationToken)
    {
        string temp = path + $".{Guid.NewGuid():N}.tmp";
        try
        {
            await File.WriteAllTextAsync(
                temp,
                rootObject.ToJsonString(new JsonSerializerOptions { WriteIndented = true }) + Environment.NewLine,
                cancellationToken).ConfigureAwait(false);
            File.Move(temp, path, overwrite: true);
        }
        finally
        {
            if (File.Exists(temp)) File.Delete(temp);
        }
    }

    private static DotNetFrameworkRequirement ParseFramework(JsonElement element, string sourcePath)
    {
        if (!element.TryGetProperty("name", out JsonElement nameElement)
            || !element.TryGetProperty("version", out JsonElement versionElement))
        {
            throw new InvalidDataException($"Runtime config '{sourcePath}' contains an incomplete framework entry.");
        }

        string? name = nameElement.GetString();
        string? versionText = versionElement.GetString();
        if (string.IsNullOrWhiteSpace(name)
            || string.IsNullOrWhiteSpace(versionText)
            || !Version.TryParse(versionText, out Version? version))
        {
            throw new InvalidDataException($"Runtime config '{sourcePath}' contains an invalid framework entry.");
        }

        return new DotNetFrameworkRequirement(name, version);
    }
}
