namespace Ueci.Unreal;

public sealed class UnrealBuildToolRunner
{
    public Task<ExternalProcessResult> RunAsync(
        string engineRoot,
        string dotNetRoot,
        IReadOnlyList<string> arguments,
        CancellationToken cancellationToken = default)
    {
        string root = Path.GetFullPath(engineRoot);
        string project = Path.Combine(
            root, "Engine", "Source", "Programs", "UnrealBuildTool", "UnrealBuildTool.csproj");
        UnrealBuildToolPaths ubt = File.Exists(project)
            ? UnrealBuildToolLocator.LocateBuiltOutput(root, project)
            : UnrealBuildToolLocator.Locate(root);
        return RunAsync(ubt, dotNetRoot, arguments, cancellationToken);
    }

    public async Task<ExternalProcessResult> RunAsync(
        UnrealBuildToolPaths ubt,
        string dotNetRoot,
        IReadOnlyList<string> arguments,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(ubt);
        string root = Path.GetFullPath(dotNetRoot);
        string dotnet = Path.Combine(root, OperatingSystem.IsWindows() ? "dotnet.exe" : "dotnet");
        if (!File.Exists(dotnet))
        {
            throw new FileNotFoundException("Epic bundled dotnet host is missing.", dotnet);
        }

        string isolatedHome = Path.Combine(ubt.EngineRoot, ".ueci", "ubt-home");
        Directory.CreateDirectory(isolatedHome);
        Directory.CreateDirectory(Path.Combine(isolatedHome, ".config"));

        var environment = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["DOTNET_ROOT"] = root,
            ["DOTNET_MULTILEVEL_LOOKUP"] = "0",
            ["DOTNET_NOLOGO"] = "1",
            ["DOTNET_CLI_TELEMETRY_OPTOUT"] = "1",
            ["DOTNET_SKIP_FIRST_TIME_EXPERIENCE"] = "1",
            ["DOTNET_CLI_WORKLOAD_UPDATE_NOTIFY_DISABLE"] = "1",
        };

        // UBT reads BuildConfiguration.xml from the user's profile as well as from the
        // project. CI builds must not inherit workstation-specific executors (for example
        // a global UBA setting) because those binaries are intentionally absent from the
        // minimal UECI working set. Use an isolated profile while still honoring the
        // project-local Saved/UnrealBuildTool/BuildConfiguration.xml generated by UECI.
        string isolatedUbtConfigDirectory;
        if (OperatingSystem.IsWindows())
        {
            environment["USERPROFILE"] = isolatedHome;
            environment["APPDATA"] = Path.Combine(isolatedHome, "AppData", "Roaming");
            environment["LOCALAPPDATA"] = Path.Combine(isolatedHome, "AppData", "Local");
            Directory.CreateDirectory(environment["APPDATA"]);
            Directory.CreateDirectory(environment["LOCALAPPDATA"]);
            isolatedUbtConfigDirectory = Path.Combine(
                environment["APPDATA"],
                "Unreal Engine",
                "UnrealBuildTool");
        }
        else
        {
            environment["HOME"] = isolatedHome;
            environment["XDG_CONFIG_HOME"] = Path.Combine(isolatedHome, ".config");
            isolatedUbtConfigDirectory = Path.Combine(
                environment["XDG_CONFIG_HOME"],
                "Unreal Engine",
                "UnrealBuildTool");
        }

        // Do not let UBT generate a fresh user-level config with executor defaults.
        // Keep all three scopes that UBT can read (Engine, isolated user, Project) on
        // the same local-executor policy. The project/engine scopes are written while
        // preparing the synthetic host; this covers the isolated user scope.
        await UnrealBuildToolConfiguration.WriteHermeticLocalExecutorAsync(
            isolatedUbtConfigDirectory,
            cancellationToken).ConfigureAwait(false);

        string[] processArguments = [ubt.AssemblyPath, .. arguments];
        return await ExternalProcess.RunAsync(
            dotnet,
            ubt.EngineRoot,
            processArguments,
            environment,
            unsetEnvironment: ["LINUX_ROOT", "LINUX_MULTIARCH_ROOT"],
            cancellationToken: cancellationToken).ConfigureAwait(false);
    }
}
