<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>ueci</AssemblyName>
    <RootNamespace>Ueci.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Ueci.Core/Ueci.Core.csproj" />
  </ItemGroup>
</Project>
