name: CodeQL

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '17 4 * * 1'

permissions:
  security-events: write
  packages: read
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: github/codeql-action/init@v4
        with:
          languages: csharp
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 8.0.x
      - run: dotnet build Ueci.sln -c Release
      - uses: github/codeql-action/analyze@v4
